// registry/vue/blocks/AppShellSidebar.vue
<script lang="ts">
import type { Component } from "vue"

export type AppNavItem = { id: string; label: string; icon?: Component; badge?: number; badgeLabel?: string; href?: string }
export type AppUser = { name: string; email?: string; avatarUrl?: string }

// Closes the mobile sheet on every click; prevents the link only when the app navigates itself.
export function handleNavigate(event: { preventDefault(): void }, id: string, onNavigate: ((id: string) => void) | undefined, close: () => void) {
  close()
  if (!onNavigate) return
  event.preventDefault()
  onNavigate(id)
}
</script>

<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { computed, defineComponent } from "vue"
import { Separator } from "@/registry/vue/ui/separator"
import {
  Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupContent, SidebarHeader, SidebarInset, SidebarMenu,
  SidebarMenuBadge, SidebarMenuButton, SidebarMenuItem, SidebarProvider, SidebarTrigger, useSidebar,
} from "@/registry/vue/ui/sidebar"
import { SaqaraLogo } from "@/registry/vue/ui/saqara-logo"
import { ThemeToggle } from "@/registry/vue/ui/theme-toggle"
import { UserMenu } from "@/registry/vue/ui/user-menu"

// Saqara block: collapsible sidebar shell. Routing-agnostic — `href` renders links, `onNavigate` (@navigate) handles clicks.
const props = withDefaults(defineProps<{
  nav: AppNavItem[]
  activeId?: string
  title?: string
  user?: AppUser
  onNavigate?: (id: string) => void
  onSignOut?: () => void
  defaultOpen?: boolean
  /** "inset" (shadcn dashboard layout): the content is a white panel framed by the sidebar colour. */
  variant?: "sidebar" | "inset"
  class?: HTMLAttributes["class"]
}>(), { defaultOpen: true, variant: "sidebar" })
const theme = defineModel<"light" | "dark">("theme")
const active = computed(() => props.nav.find((item) => item.id === props.activeId))

// Renderless child of SidebarProvider: exposes the mobile-sheet closer to the nav slot.
const SidebarCloser = defineComponent((_, { slots }) => {
  const { setOpenMobile } = useSidebar()
  return () => slots.default?.({ close: () => setOpenMobile(false) })
})
</script>

<template>
  <SidebarProvider :default-open="defaultOpen" :class="props.class">
    <Sidebar collapsible="icon" :variant="variant">
      <SidebarHeader>
        <div class="flex h-8 items-center px-1 group-data-[collapsible=icon]:justify-center">
          <slot name="logo"><SaqaraLogo with-text class="group-data-[collapsible=icon]:[&>span]:sr-only" /></slot>
        </div>
      </SidebarHeader>
      <SidebarContent>
        <SidebarGroup>
          <SidebarGroupContent>
            <SidebarCloser v-slot="{ close }">
            <SidebarMenu>
              <SidebarMenuItem v-for="item in nav" :key="item.id">
                <SidebarMenuButton
                  :is-active="item.id === activeId"
                  :tooltip="item.label"
                  :aria-current="item.id === activeId ? 'page' : undefined"
                  :as="item.href ? 'a' : 'button'"
                  :href="item.href"
                  @click="handleNavigate($event, item.id, onNavigate, close)"
                >
                  <component :is="item.icon" v-if="item.icon" />
                  <!-- The count is shown by the badge (outside the button): its spoken context lives inside the label. -->
                  <span>{{ item.label }}<span v-if="item.badge" class="sr-only"> {{ item.badgeLabel ?? `${item.badge} en attente` }}</span></span>
                </SidebarMenuButton>
                <SidebarMenuBadge v-if="item.badge" aria-hidden="true" class="justify-center rounded-full bg-identity text-identity-foreground peer-hover/menu-button:text-identity-foreground peer-data-[active=true]/menu-button:text-identity-foreground">{{ item.badge }}</SidebarMenuBadge>
              </SidebarMenuItem>
            </SidebarMenu>
            </SidebarCloser>
          </SidebarGroupContent>
        </SidebarGroup>
      </SidebarContent>
      <SidebarFooter v-if="user">
        <UserMenu v-bind="user" :on-sign-out="onSignOut" class="w-full group-data-[collapsible=icon]:[&>span:last-child]:hidden">
          <template v-if="$slots['user-menu']" #default><slot name="user-menu" /></template>
        </UserMenu>
      </SidebarFooter>
    </Sidebar>
    <!-- min-h-0 + overflow: in a height-bounded shell the white panel scrolls inside its frame instead of spilling out. -->
    <SidebarInset class="min-h-0 overflow-y-auto">
      <header class="flex h-14 shrink-0 items-center gap-2 border-b px-4">
        <SidebarTrigger class="-ml-1" />
        <Separator orientation="vertical" class="mr-2 data-[orientation=vertical]:h-4" />
        <component :is="active.icon" v-if="active?.icon" class="size-4 text-primary" />
        <h1 v-if="title ?? active?.label" class="text-sm font-medium">{{ title ?? active?.label }}</h1>
        <ThemeToggle v-if="theme" v-model:theme="theme" class="ml-auto" />
      </header>
      <div class="flex-1 p-4"><slot /></div>
    </SidebarInset>
  </SidebarProvider>
</template>

// registry/react/blocks/app-shell-sidebar.tsx
"use client"

import * as React from "react"
import { Separator } from "@/registry/react/ui/separator"
import {
  Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupContent, SidebarHeader, SidebarInset, SidebarMenu,
  SidebarMenuBadge, SidebarMenuButton, SidebarMenuItem, SidebarProvider, SidebarTrigger, useSidebar,
} from "@/registry/react/ui/sidebar"
import { SaqaraLogo } from "@/registry/react/ui/saqara-logo"
import { ThemeToggle } from "@/registry/react/ui/theme-toggle"
import { UserMenu } from "@/registry/react/ui/user-menu"

export type AppNavItem = { id: string; label: string; icon?: React.ComponentType<{ className?: string }>; badge?: number; badgeLabel?: string; href?: string }
export type AppUser = { name: string; email?: string; avatarUrl?: string }

// Closes the mobile sheet on every click; prevents the link only when the app navigates itself.
export function handleNavigate(event: { preventDefault(): void }, id: string, onNavigate: ((id: string) => void) | undefined, close: () => void) {
  close()
  if (!onNavigate) return
  event.preventDefault()
  onNavigate(id)
}

function NavMenu({ nav, activeId, onNavigate }: { nav: AppNavItem[]; activeId?: string; onNavigate?: (id: string) => void }) {
  const { setOpenMobile } = useSidebar()
  return (
    <SidebarMenu>
      {nav.map((item) => {
        const isActive = item.id === activeId
        const Icon = item.icon
        // The count is shown by the badge (outside the button): its spoken context lives inside the label.
        const badgeText = item.badge ? <span className="sr-only"> {item.badgeLabel ?? `${item.badge} en attente`}</span> : null
        const content = (<>{Icon && <Icon />}<span>{item.label}{badgeText}</span></>)
        return (
          <SidebarMenuItem key={item.id}>
            <SidebarMenuButton
              isActive={isActive}
              tooltip={item.label}
              aria-current={isActive ? "page" : undefined}
              asChild={!!item.href}
              onClick={(event) => handleNavigate(event, item.id, onNavigate, () => setOpenMobile(false))}
            >
              {item.href ? <a href={item.href}>{content}</a> : content}
            </SidebarMenuButton>
            {!!item.badge && <SidebarMenuBadge aria-hidden="true" className="justify-center rounded-full bg-identity text-identity-foreground peer-hover/menu-button:text-identity-foreground peer-data-[active=true]/menu-button:text-identity-foreground">{item.badge}</SidebarMenuBadge>}
          </SidebarMenuItem>
        )
      })}
    </SidebarMenu>
  )
}

type AppShellSidebarProps = {
  nav: AppNavItem[]
  activeId?: string
  onNavigate?: (id: string) => void
  title?: React.ReactNode
  logo?: React.ReactNode
  user?: AppUser
  onSignOut?: () => void
  userMenuItems?: React.ReactNode
  theme?: "light" | "dark"
  onThemeChange?: (theme: "light" | "dark") => void
  defaultOpen?: boolean
  /** "inset" (shadcn dashboard layout): the content is a white panel framed by the sidebar colour. */
  variant?: "sidebar" | "inset"
  className?: string
  children?: React.ReactNode
}

// Saqara block: collapsible sidebar shell. Routing-agnostic — `href` renders links, `onNavigate` handles clicks.
function AppShellSidebar({
  nav, activeId, onNavigate, title, logo, user, onSignOut, userMenuItems, theme, onThemeChange, defaultOpen = true, variant = "sidebar", className, children,
}: AppShellSidebarProps) {
  const active = nav.find((item) => item.id === activeId)
  const PageIcon = active?.icon

  return (
    <SidebarProvider defaultOpen={defaultOpen} className={className}>
      <Sidebar collapsible="icon" variant={variant}>
        <SidebarHeader>
          <div className="flex h-8 items-center px-1 group-data-[collapsible=icon]:justify-center">
            {logo ?? <SaqaraLogo withText className="group-data-[collapsible=icon]:[&>span]:sr-only" />}
          </div>
        </SidebarHeader>
        <SidebarContent>
          <SidebarGroup>
            <SidebarGroupContent>
              <NavMenu nav={nav} activeId={activeId} onNavigate={onNavigate} />
            </SidebarGroupContent>
          </SidebarGroup>
        </SidebarContent>
        {user && (
          <SidebarFooter>
            <UserMenu {...user} onSignOut={onSignOut} className="w-full group-data-[collapsible=icon]:[&>span:last-child]:hidden">
              {userMenuItems}
            </UserMenu>
          </SidebarFooter>
        )}
      </Sidebar>
      {/* min-h-0 + overflow: in a height-bounded shell the white panel scrolls inside its frame instead of spilling out. */}
      <SidebarInset className="min-h-0 overflow-y-auto">
        <header className="flex h-14 shrink-0 items-center gap-2 border-b px-4">
          <SidebarTrigger className="-ml-1" />
          <Separator orientation="vertical" className="mr-2 data-[orientation=vertical]:h-4" />
          {PageIcon && <PageIcon className="size-4 text-primary" />}
          {(title ?? active?.label) && <h1 className="text-sm font-medium">{title ?? active?.label}</h1>}
          {theme && onThemeChange && <ThemeToggle theme={theme} onThemeChange={onThemeChange} className="ml-auto" />}
        </header>
        <div className="flex-1 p-4">{children}</div>
      </SidebarInset>
    </SidebarProvider>
  )
}

export { AppShellSidebar }
