// src/vue/demos/user-menu.vue
<script setup lang="ts">
import { Settings } from "@lucide/vue"
import { DropdownMenuItem } from "@/registry/vue/ui/dropdown-menu"
import { UserMenu } from "@/registry/vue/ui/user-menu"
</script>

<template>
  <UserMenu name="Alexandre Brochot" email="alexandre.brochot@saqara.com" @sign-out="() => {}">
    <DropdownMenuItem><Settings />Mon profil</DropdownMenuItem>
  </UserMenu>
</template>

// src/react/demos/user-menu.tsx
import { Settings } from "lucide-react"
import { DropdownMenuItem } from "@/registry/react/ui/dropdown-menu"
import { UserMenu } from "@/registry/react/ui/user-menu"

export default function UserMenuDemo() {
  return (
    <UserMenu name="Alexandre Brochot" email="alexandre.brochot@saqara.com" onSignOut={() => {}}>
      <DropdownMenuItem><Settings />Mon profil</DropdownMenuItem>
    </UserMenu>
  )
}
