// registry/react/ui/textarea.tsx
import * as React from "react"
import { cn } from "cn"

// Saqara: `rows` is a minimum height (field-sizing-content ignores it); `autoResize={false}` keeps a fixed height.
function Textarea({ className, rows, autoResize = true, style, ...props }: React.ComponentProps<"textarea"> & { autoResize?: boolean }) {
  return (
    <textarea
      data-slot="textarea"
      rows={rows}
      style={rows ? { minHeight: `calc(${rows}lh + 1rem + 2px)`, ...style } : style}
      className={cn(
        "flex min-h-16 w-full rounded-md border border-input bg-transparent [&[readonly]]:bg-muted/40 dark:[&[readonly]]:bg-muted/40 px-3 py-2 text-base shadow-xs transition-[color,box-shadow] outline-none placeholder:text-muted-foreground focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-destructive/20 md:text-sm dark:bg-input/30 dark:aria-invalid:ring-destructive/40",
        autoResize && "field-sizing-content",
        className
      )}
      {...props}
    />
  )
}

export { Textarea }

// registry/vue/ui/textarea/Textarea.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { useVModel } from "@vueuse/core"
import { cn } from "@/lib/utils"

// Saqara: `rows` is a minimum height (field-sizing-content ignores it); `:auto-resize="false"` keeps a fixed height.
const props = withDefaults(defineProps<{
  class?: HTMLAttributes["class"]
  defaultValue?: string | number
  modelValue?: string | number
  rows?: number
  autoResize?: boolean
}>(), { autoResize: true })

const emits = defineEmits<{
  (e: "update:modelValue", payload: string | number): void
}>()

const modelValue = useVModel(props, "modelValue", emits, {
  passive: true,
  defaultValue: props.defaultValue,
})
</script>

<template>
  <textarea
    v-model="modelValue"
    data-slot="textarea"
    :rows="rows"
    :style="rows ? { minHeight: `calc(${rows}lh + 1rem + 2px)` } : undefined"
    :class="cn('border-input placeholder:text-muted-foreground focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive dark:bg-input/30 flex min-h-16 w-full rounded-md border bg-transparent [&[readonly]]:bg-muted/40 dark:[&[readonly]]:bg-muted/40 px-3 py-2 text-base shadow-xs transition-[color,box-shadow] outline-none focus-visible:ring-3 disabled:cursor-not-allowed disabled:opacity-50 md:text-sm', autoResize && 'field-sizing-content', props.class)"
  />
</template>
