// registry/vue/ui/autocomplete/Autocomplete.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import type { AutocompleteOption } from "./utils"
import { computed, onBeforeUnmount, ref, useId, watch } from "vue"
import { cn } from "@/lib/utils"
import { Input } from "@/registry/vue/ui/input"
import { Spinner } from "@/registry/vue/ui/spinner"

// Saqara: a normal Input with a suggestion list (address search…). Focus never leaves the field;
// the app owns fetching, debouncing and what a selection does (@select). Attributes go to the input.
defineOptions({ inheritAttrs: false })
const props = withDefaults(defineProps<{
  /** Suggestions for the current text: the app fetches them (async) and passes them back. */
  suggestions: AutocompleteOption[]
  loading?: boolean
  loadingMessage?: string
  /** Shown when a search returns nothing. None by default. */
  emptyMessage?: string
  inputClass?: HTMLAttributes["class"]
  /** Minimum length before the list (or its messages) shows. */
  minChars?: number
  onSelect?: (option: AutocompleteOption) => void
  class?: HTMLAttributes["class"]
}>(), { loading: false, loadingMessage: "Recherche…", minChars: 1 })
/** v-model:value — the typed text. */
const value = defineModel<string>("value", { default: "" })
/** #icon: leading icon inside the field (search, map pin…). */
const slots = defineSlots<{ suggestion?: (props: { option: AutocompleteOption }) => unknown, icon?: () => unknown }>()

const listId = useId()
const open = ref(false)
const active = ref(0)
const enough = computed(() => value.value.trim().length >= props.minChars)
// The previous suggestions stay visible while the next search runs (spinner in the field).
const showList = computed(() => open.value && enough.value && props.suggestions.length > 0)
const status = computed(() => open.value && enough.value && props.suggestions.length === 0 ? (props.loading ? props.loadingMessage : props.emptyMessage) ?? "" : "")

// Escape closes the list first. A dialog (reka DismissableLayer) listens on the document, so the list
// listens one step earlier, on the window in the capture phase, while it is open.
function onEscape(event: KeyboardEvent) {
  if (event.key !== "Escape") return
  event.stopPropagation()
  open.value = false
}
watch(showList, (shown) => {
  if (shown) window.addEventListener("keydown", onEscape, true)
  else window.removeEventListener("keydown", onEscape, true)
})
onBeforeUnmount(() => window.removeEventListener("keydown", onEscape, true))

function pick(option: AutocompleteOption) {
  props.onSelect?.(option)
  open.value = false
  active.value = 0
}
function onInput(event: Event) {
  value.value = (event.target as HTMLInputElement).value
  open.value = true
  active.value = 0
}
function onKeydown(event: KeyboardEvent) {
  if (event.key === "ArrowDown" && props.suggestions.length) {
    event.preventDefault()
    if (!open.value) open.value = true
    else active.value = Math.min(active.value + 1, props.suggestions.length - 1)
  } else if (event.key === "ArrowUp" && props.suggestions.length) {
    event.preventDefault()
    active.value = Math.max(active.value - 1, 0)
  } else if (event.key === "Enter" && showList.value) {
    event.preventDefault()
    pick(props.suggestions[active.value]!)
  } else if (event.key === "Escape") {
    open.value = false
  }
}
</script>

<template>
  <div data-slot="autocomplete" :class="cn('relative', props.class)">
    <Input
      v-bind="$attrs"
      role="combobox"
      :aria-expanded="showList"
      :aria-controls="listId"
      aria-autocomplete="list"
      :aria-activedescendant="showList ? `${listId}-${active}` : undefined"
      autocomplete="off"
      :model-value="value"
      :class="cn(slots.icon && 'pl-9', loading && 'pr-8', inputClass)"
      @input="onInput"
      @keydown="onKeydown"
      @focus="open = true"
      @blur="open = false"
    />
    <span v-if="$slots.icon" aria-hidden="true" class="pointer-events-none absolute top-1/2 left-3 -translate-y-1/2 text-muted-foreground [&>svg]:size-4"><slot name="icon" /></span>
    <Spinner v-if="loading" aria-hidden="true" role="presentation" class="absolute top-1/2 right-2.5 -translate-y-1/2 text-muted-foreground" />
    <ul v-if="showList" :id="listId" role="listbox" class="absolute z-50 mt-1 max-h-60 w-full overflow-auto rounded-md border bg-popover p-1 text-popover-foreground shadow-md">
      <li v-for="(option, i) in suggestions" :id="`${listId}-${i}`" :key="option.value" role="option" :aria-selected="i === active"
        :class="cn('cursor-pointer rounded-sm px-2 py-1.5 text-sm', i === active && 'bg-accent text-accent-foreground')"
        @mousedown.prevent="pick(option)" @mouseenter="active = i">
        <slot name="suggestion" :option="option">
          <span class="block">{{ option.label }}</span>
          <span v-if="option.description" class="block text-xs text-muted-foreground">{{ option.description }}</span>
        </slot>
      </li>
    </ul>
    <div v-if="status" role="status" class="absolute z-50 mt-1 w-full rounded-md border bg-popover px-3 py-2 text-sm text-muted-foreground shadow-md">
      {{ status }}
    </div>
  </div>
</template>

// registry/react/ui/autocomplete.tsx
"use client"

import * as React from "react"
import { cn } from "cn"

import { Input } from "@/registry/react/ui/input"
import { Spinner } from "@/registry/react/ui/spinner"

export type AutocompleteOption = { value: string; label: string; description?: string }

type AutocompleteProps = Omit<React.ComponentProps<"input">, "value" | "onChange" | "onSelect"> & {
  /** The typed text (controlled). */
  value: string
  onValueChange?: (value: string) => void
  /** Suggestions for the current text: the app fetches them (async) and passes them back. */
  suggestions: AutocompleteOption[]
  onSelect?: (option: AutocompleteOption) => void
  loading?: boolean
  loadingMessage?: string
  /** Shown when a search returns nothing. None by default. */
  emptyMessage?: string
  /** Leading icon inside the field (search, map pin…). */
  icon?: React.ReactNode
  inputClassName?: string
  /** Minimum length before the list (or its messages) shows. */
  minChars?: number
  renderSuggestion?: (option: AutocompleteOption) => React.ReactNode
}

// Saqara: a normal Input with a suggestion list (address search…). Focus never leaves the field;
// the app owns fetching, debouncing and what a selection does.
function Autocomplete({
  value, onValueChange, suggestions, onSelect, loading = false, loadingMessage = "Recherche…", emptyMessage,
  minChars = 1, renderSuggestion, icon, inputClassName, className, onKeyDown, onFocus, onBlur, ...props
}: AutocompleteProps) {
  const listId = React.useId()
  const [open, setOpen] = React.useState(false)
  const [active, setActive] = React.useState(0)
  const enough = value.trim().length >= minChars
  // The previous suggestions stay visible while the next search runs (spinner in the field).
  const showList = open && enough && suggestions.length > 0
  const status = open && enough && suggestions.length === 0 && (loading ? loadingMessage : emptyMessage)

  // Escape closes the list first. A dialog (Radix DismissableLayer) listens on the document in the
  // capture phase, so the list listens one step earlier, on the window, while it is open.
  React.useEffect(() => {
    if (!showList) return
    const onEscape = (event: KeyboardEvent) => {
      if (event.key !== "Escape") return
      event.stopPropagation()
      setOpen(false)
    }
    window.addEventListener("keydown", onEscape, true)
    return () => window.removeEventListener("keydown", onEscape, true)
  }, [showList])

  const pick = (option: AutocompleteOption) => {
    onSelect?.(option)
    setOpen(false)
    setActive(0)
  }

  return (
    <div data-slot="autocomplete" className={cn("relative", className)}>
      <Input
        role="combobox"
        aria-expanded={showList}
        aria-controls={listId}
        aria-autocomplete="list"
        aria-activedescendant={showList ? `${listId}-${active}` : undefined}
        autoComplete="off"
        value={value}
        className={cn(icon && "pl-9", loading && "pr-8", inputClassName)}
        onChange={(event) => { onValueChange?.(event.target.value); setOpen(true); setActive(0) }}
        onFocus={(event) => { setOpen(true); onFocus?.(event) }}
        onBlur={(event) => { setOpen(false); onBlur?.(event) }}
        onKeyDown={(event) => {
          onKeyDown?.(event)
          if (event.key === "ArrowDown" && suggestions.length) {
            event.preventDefault()
            if (!open) setOpen(true)
            else setActive((i) => Math.min(i + 1, suggestions.length - 1))
          } else if (event.key === "ArrowUp" && suggestions.length) {
            event.preventDefault()
            setActive((i) => Math.max(i - 1, 0))
          } else if (event.key === "Enter" && showList) {
            event.preventDefault()
            pick(suggestions[active])
          } else if (event.key === "Escape") {
            setOpen(false)
          }
        }}
        {...props}
      />
      {icon && <span aria-hidden="true" className="pointer-events-none absolute top-1/2 left-3 -translate-y-1/2 text-muted-foreground [&>svg]:size-4">{icon}</span>}
      {loading && <Spinner aria-hidden="true" role="presentation" className="absolute top-1/2 right-2.5 -translate-y-1/2 text-muted-foreground" />}
      {showList && (
        <ul id={listId} role="listbox" className="absolute z-50 mt-1 max-h-60 w-full overflow-auto rounded-md border bg-popover p-1 text-popover-foreground shadow-md">
          {suggestions.map((option, i) => (
            <li key={option.value} id={`${listId}-${i}`} role="option" aria-selected={i === active}
              className={cn("cursor-pointer rounded-sm px-2 py-1.5 text-sm", i === active && "bg-accent text-accent-foreground")}
              onMouseDown={(event) => { event.preventDefault(); pick(option) }}
              onMouseEnter={() => setActive(i)}>
              {renderSuggestion ? renderSuggestion(option) : (
                <>
                  <span className="block">{option.label}</span>
                  {option.description && <span className="block text-xs text-muted-foreground">{option.description}</span>}
                </>
              )}
            </li>
          ))}
        </ul>
      )}
      {status && (
        <div role="status" className="absolute z-50 mt-1 w-full rounded-md border bg-popover px-3 py-2 text-sm text-muted-foreground shadow-md">
          {status}
        </div>
      )}
    </div>
  )
}

export { Autocomplete }
