// registry/vue/ui/radio-group/RadioGroup.vue
<script setup lang="ts">
import type { AcceptableValue, RadioGroupRootEmits, RadioGroupRootProps } from "reka-ui"
import type { HTMLAttributes } from "vue"
import { reactiveOmit } from "@vueuse/core"
import { RadioGroupRoot, useForwardProps } from "reka-ui"
import { computed, ref } from "vue"
import { cn } from "@/lib/utils"

// Saqara: `allowDeselect` — clicking the checked item again clears the selection (value "").
const props = defineProps<RadioGroupRootProps & { class?: HTMLAttributes["class"], allowDeselect?: boolean }>()
const emits = defineEmits<RadioGroupRootEmits>()

const delegatedProps = reactiveOmit(props, "class", "allowDeselect", "modelValue", "defaultValue")
const forwarded = useForwardProps(delegatedProps)

const inner = ref<AcceptableValue | undefined>(props.defaultValue ?? "")
const value = computed(() => props.modelValue !== undefined ? props.modelValue : inner.value)
function change(next: AcceptableValue) {
  inner.value = next
  emits("update:modelValue", next)
}
function onClickCapture(event: MouseEvent) {
  const item = (event.target as Element).closest("[role=radio]")
  if (!props.allowDeselect || item?.getAttribute("aria-checked") !== "true") return
  event.preventDefault()
  event.stopPropagation()
  change("")
}
</script>

<template>
  <RadioGroupRoot
    v-slot="slotProps"
    data-slot="radio-group"
    :class="cn('grid gap-3', props.class)"
    v-bind="forwarded"
    :model-value="value"
    @update:model-value="change"
    @click.capture="onClickCapture"
  >
    <slot v-bind="slotProps" />
  </RadioGroupRoot>
</template>

// registry/react/ui/radio-group.tsx
"use client"

import * as React from "react"
import { cn } from "cn"
import { CircleIcon } from "lucide-react"
import { RadioGroup as RadioGroupPrimitive } from "radix-ui"

// Saqara: `allowDeselect` — clicking the checked item again clears the selection (value "").
function RadioGroup({
  className,
  allowDeselect = false,
  value: valueProp,
  defaultValue,
  onValueChange,
  onClickCapture,
  ...props
}: React.ComponentProps<typeof RadioGroupPrimitive.Root> & { allowDeselect?: boolean }) {
  const [inner, setInner] = React.useState(defaultValue ?? "")
  const value = valueProp ?? inner
  const change = (next: string) => {
    setInner(next)
    onValueChange?.(next)
  }
  return (
    <RadioGroupPrimitive.Root
      data-slot="radio-group"
      className={cn("grid gap-3", className)}
      value={value}
      onValueChange={change}
      onClickCapture={(event) => {
        onClickCapture?.(event)
        const item = (event.target as Element).closest("[role=radio]")
        if (!allowDeselect || item?.getAttribute("aria-checked") !== "true") return
        event.preventDefault()
        event.stopPropagation()
        change("")
      }}
      {...props}
    />
  )
}

function RadioGroupItem({
  className,
  ...props
}: React.ComponentProps<typeof RadioGroupPrimitive.Item>) {
  return (
    <RadioGroupPrimitive.Item
      data-slot="radio-group-item"
      className={cn(
        "aspect-square size-4 shrink-0 rounded-full border border-input text-primary shadow-xs transition-[color,box-shadow] outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-destructive/20 dark:bg-input/30 dark:aria-invalid:ring-destructive/40",
        className
      )}
      {...props}
    >
      <RadioGroupPrimitive.Indicator
        data-slot="radio-group-indicator"
        className="relative flex items-center justify-center"
      >
        <CircleIcon className="absolute top-1/2 left-1/2 size-2 -translate-x-1/2 -translate-y-1/2 fill-primary" />
      </RadioGroupPrimitive.Indicator>
    </RadioGroupPrimitive.Item>
  )
}

export { RadioGroup, RadioGroupItem }
