// registry/vue/ui/table/Table.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

// Saqara: framed like data-table (rounded border on the scroll container); attributes go to the <table>;
// `:container="false"` drops the wrapper (and its frame), so sticky cells can stick to an outer scroller;
// `:bordered="false"` drops the frame (a card frames it); `wrap` lets cells wrap (long messages).
defineOptions({ inheritAttrs: false })
const props = withDefaults(defineProps<{
  class?: HTMLAttributes["class"]
  container?: boolean
  bordered?: boolean
  wrap?: boolean
}>(), { container: true, bordered: true, wrap: false })
</script>

<template>
  <div v-if="container" data-slot="table-container" :class="cn('relative w-full overflow-auto', bordered && 'rounded-md border')">
    <table data-slot="table" v-bind="$attrs" :class="cn('w-full caption-bottom text-sm', wrap && '[&_td]:whitespace-normal', props.class)">
      <slot />
    </table>
  </div>
  <table v-else data-slot="table" v-bind="$attrs" :class="cn('w-full caption-bottom text-sm', wrap && '[&_td]:whitespace-normal', props.class)">
    <slot />
  </table>
</template>

// registry/react/ui/table.tsx
"use client"

import * as React from "react"
import { cn } from "cn"

// Saqara: framed like data-table (rounded border on the scroll container);
// `container={false}` drops the wrapper (and its frame), so sticky cells can stick to an outer scroller.
// `bordered={false}` drops the frame (a card frames it); `wrap` lets cells wrap (long messages).
function Table({ className, container = true, bordered = true, wrap = false, ...props }: React.ComponentProps<"table"> & {
  container?: boolean
  bordered?: boolean
  wrap?: boolean
}) {
  const table = (
    <table
      data-slot="table"
      className={cn("w-full caption-bottom text-sm", wrap && "[&_td]:whitespace-normal", className)}
      {...props}
    />
  )
  if (!container) return table
  return (
    <div
      data-slot="table-container"
      className={cn("relative w-full overflow-x-auto", bordered && "rounded-md border")}
    >
      {table}
    </div>
  )
}

function TableHeader({ className, ...props }: React.ComponentProps<"thead">) {
  return (
    <thead
      data-slot="table-header"
      className={cn("[&_tr]:border-b", className)}
      {...props}
    />
  )
}

function TableBody({ className, ...props }: React.ComponentProps<"tbody">) {
  return (
    <tbody
      data-slot="table-body"
      className={cn("[&_tr:last-child]:border-0", className)}
      {...props}
    />
  )
}

function TableFooter({ className, ...props }: React.ComponentProps<"tfoot">) {
  return (
    <tfoot
      data-slot="table-footer"
      className={cn(
        "border-t bg-muted/50 font-medium [&>tr]:last:border-b-0",
        className
      )}
      {...props}
    />
  )
}

function TableRow({ className, ...props }: React.ComponentProps<"tr">) {
  return (
    <tr
      data-slot="table-row"
      className={cn(
        "border-b transition-colors hover:bg-muted/50 has-aria-expanded:bg-muted/50 data-[state=selected]:bg-muted",
        className
      )}
      {...props}
    />
  )
}

function TableHead({ className, ...props }: React.ComponentProps<"th">) {
  return (
    <th
      data-slot="table-head"
      className={cn(
        "h-10 px-2 text-left align-middle font-medium whitespace-nowrap text-foreground [&:has([role=checkbox])]:pr-0 [&>[role=checkbox]]:translate-y-[2px]",
        className
      )}
      {...props}
    />
  )
}

function TableCell({ className, ...props }: React.ComponentProps<"td">) {
  return (
    <td
      data-slot="table-cell"
      className={cn(
        "p-2 align-middle whitespace-nowrap [&:has([role=checkbox])]:pr-0 [&>[role=checkbox]]:translate-y-[2px]",
        className
      )}
      {...props}
    />
  )
}

function TableCaption({
  className,
  ...props
}: React.ComponentProps<"caption">) {
  return (
    <caption
      data-slot="table-caption"
      className={cn("mt-4 text-sm text-muted-foreground", className)}
      {...props}
    />
  )
}

export {
  Table,
  TableHeader,
  TableBody,
  TableFooter,
  TableHead,
  TableRow,
  TableCell,
  TableCaption,
}
