// registry/vue/ui/tag-input/TagInput.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { XIcon } from "@lucide/vue"
import { computed, ref, useId } from "vue"
import { cn } from "@/lib/utils"
import { Badge } from "@/registry/vue/ui/badge"
import { addTags, filterSuggestions } from "./utils"

// Saqara: free entry (e-mails, SIRET…) or a catalogue with suggestions (tags); replaces MultiInput / TagCombobox.
// Extra attributes (aria-label, name…) belong to the input, not the wrapper.
defineOptions({ inheritAttrs: false })
const props = withDefaults(defineProps<{
  suggestions?: string[]
  allowCreate?: boolean
  maxTags?: number
  placeholder?: string
  removeLabel?: string
  disabled?: boolean
  id?: string
  maxSuggestions?: number
  /** Shown when the typed text matches no suggestion. Default: "Aucun résultat." for a closed catalogue. */
  emptyMessage?: string
  /** "Pick only" (@select): a chosen value goes there and the field clears; no tag is added. */
  onSelect?: (value: string) => void
  class?: HTMLAttributes["class"]
}>(), { allowCreate: true, placeholder: "Ajouter…", removeLabel: "Retirer", disabled: false, maxSuggestions: 8 })
const model = defineModel<string[]>({ default: () => [] })
/** v-model:query, e.g. for a server search. */
const query = defineModel<string>("query", { default: "" })
defineSlots<{ suggestion?: (props: { suggestion: string }) => unknown }>()

const input = ref<HTMLInputElement>()
const listId = useId()
const open = ref(false)
const active = ref(0)
const options = computed(() => (props.suggestions ? filterSuggestions(props.suggestions, query.value, model.value, props.maxSuggestions) : []))
const full = computed(() => props.maxTags !== undefined && model.value.length >= props.maxTags)
const showList = computed(() => open.value && options.value.length > 0 && !full.value)
const empty = computed(() => props.emptyMessage ?? (props.allowCreate ? undefined : "Aucun résultat."))
const showEmpty = computed(() => open.value && !!props.suggestions && !!empty.value && !!query.value.trim() && options.value.length === 0 && !full.value)

function commit(raws: string[]) {
  if (props.onSelect) {
    // Same normalisation and catalogue rules as tags, one value at a time.
    for (const picked of addTags([], raws, { suggestions: props.suggestions, allowCreate: props.allowCreate })) props.onSelect(picked)
  } else {
    const next = addTags(model.value, raws, { suggestions: props.suggestions, allowCreate: props.allowCreate, maxTags: props.maxTags })
    if (next !== model.value) model.value = next
  }
  query.value = ""
  active.value = 0
}
function onInput(event: Event) {
  // Typed or pasted commas split entries; the text after the last comma stays in the field.
  const parts = (event.target as HTMLInputElement).value.split(",")
  if (parts.length > 1) commit(parts.slice(0, -1))
  query.value = parts[parts.length - 1] ?? ""
  open.value = true
  active.value = 0
}
function onKeydown(event: KeyboardEvent) {
  if (event.key === "Enter") {
    event.preventDefault()
    if (showList.value && (query.value.trim() || !props.allowCreate)) commit([options.value[active.value]!])
    else if (query.value.trim()) commit([query.value])
  } else if (event.key === "Backspace" && !query.value && model.value.length) {
    model.value = model.value.slice(0, -1)
  } else if (event.key === "ArrowDown" && options.value.length) {
    event.preventDefault()
    open.value = true
    active.value = Math.min(active.value + 1, options.value.length - 1)
  } else if (event.key === "ArrowUp" && options.value.length) {
    event.preventDefault()
    active.value = Math.max(active.value - 1, 0)
  } else if (event.key === "Escape") {
    open.value = false
  }
}
function onBlur() {
  open.value = false
  if (query.value.trim() && props.allowCreate && !props.onSelect) commit([query.value])
}
const remove = (tag: string) => { model.value = model.value.filter((t) => t !== tag) }
</script>

<template>
  <div data-slot="tag-input" :class="cn('relative', props.class)">
    <div
      class="flex min-h-9 w-full flex-wrap items-center gap-1 rounded-md border border-input bg-card px-2 py-1 text-sm shadow-xs transition-[color,box-shadow] focus-within:border-ring focus-within:ring-[3px] focus-within:ring-ring/50 dark:bg-input/30"
      @click="input?.focus()"
    >
      <Badge v-for="tag in model" :key="tag" variant="secondary" class="gap-1 pr-1">
        {{ tag }}
        <button type="button" :aria-label="`${removeLabel} ${tag}`" :disabled="disabled"
          class="rounded-sm opacity-70 outline-none hover:opacity-100 focus-visible:ring-2 focus-visible:ring-ring" @click="remove(tag)">
          <XIcon class="size-3" />
        </button>
      </Badge>
      <input
        v-bind="$attrs"
        :id="id"
        ref="input"
        role="combobox"
        :aria-expanded="showList"
        :aria-controls="listId"
        aria-autocomplete="list"
        :aria-activedescendant="showList ? `${listId}-${active}` : undefined"
        :value="query"
        :disabled="disabled || full"
        :placeholder="model.length ? undefined : placeholder"
        class="min-w-24 flex-1 bg-transparent py-0.5 outline-none placeholder:text-muted-foreground disabled:cursor-not-allowed"
        @input="onInput"
        @keydown="onKeydown"
        @focus="open = true"
        @blur="onBlur"
      >
    </div>
    <ul v-if="showList" :id="listId" role="listbox" class="absolute z-50 mt-1 max-h-60 w-full overflow-auto rounded-md border bg-popover p-1 text-popover-foreground shadow-md">
      <li v-for="(option, i) in options" :id="`${listId}-${i}`" :key="option" role="option" :aria-selected="i === active"
        :class="cn('cursor-pointer rounded-sm px-2 py-1.5 text-sm', i === active && 'bg-accent text-accent-foreground')"
        @mousedown.prevent="commit([option])" @mouseenter="active = i">
        <slot name="suggestion" :suggestion="option">{{ option }}</slot>
      </li>
    </ul>
    <div v-if="showEmpty" role="status" class="absolute z-50 mt-1 w-full rounded-md border bg-popover px-3 py-2 text-sm text-muted-foreground shadow-md">
      {{ empty }}
    </div>
  </div>
</template>

// registry/react/ui/tag-input.tsx
"use client"

import * as React from "react"
import { XIcon } from "lucide-react"
import { cn } from "cn"
import { Badge } from "@/registry/react/ui/badge"

export type TagOptions = { suggestions?: string[]; allowCreate?: boolean; maxTags?: number }

const fold = (s: string) => s.normalize("NFD").replace(/\p{Diacritic}/gu, "").toLowerCase()
const normalize = (s: string) => s.trim().replace(/\s+/g, " ")

// Adds raw entries one by one: trimmed, deduplicated (case and accents), catalogue spelling, maxTags.
export function addTags(values: string[], raws: string[], { suggestions, allowCreate = true, maxTags }: TagOptions): string[] {
  let next = values
  for (const raw of raws) {
    const tag = normalize(raw)
    if (!tag || (maxTags !== undefined && next.length >= maxTags)) continue
    if (next.some((v) => fold(v) === fold(tag))) continue
    const known = suggestions?.find((s) => fold(s) === fold(tag))
    if (!known && !allowCreate) continue
    next = [...next, known ?? tag]
  }
  return next
}

export function filterSuggestions(suggestions: string[], query: string, values: string[], limit = 8): string[] {
  const q = fold(normalize(query))
  const chosen = new Set(values.map(fold))
  return suggestions.filter((s) => !chosen.has(fold(s)) && fold(s).includes(q)).slice(0, limit)
}

type TagInputProps = TagOptions & {
  value?: string[]
  onValueChange?: (value: string[]) => void
  /** "Pick only": a chosen value goes to onSelect and the field clears; no tag is added. */
  onSelect?: (value: string) => void
  /** Controlled query, e.g. for a server search. */
  query?: string
  onQueryChange?: (query: string) => void
  maxSuggestions?: number
  renderSuggestion?: (suggestion: string) => React.ReactNode
  /** Shown when the typed text matches no suggestion. Default: "Aucun résultat." for a closed catalogue. */
  emptyMessage?: React.ReactNode
  placeholder?: string
  removeLabel?: string
  disabled?: boolean
  id?: string
  "aria-label"?: string
  className?: string
}

// Saqara: free entry (e-mails, SIRET…) or a catalogue with suggestions (tags); replaces MultiInput / TagCombobox.
function TagInput({
  value = [], onValueChange, onSelect, query: controlledQuery, onQueryChange, suggestions, allowCreate = true, maxTags,
  maxSuggestions = 8, renderSuggestion, emptyMessage = allowCreate ? undefined : "Aucun résultat.",
  placeholder = "Ajouter…", removeLabel = "Retirer", disabled = false, id, "aria-label": ariaLabel, className,
}: TagInputProps) {
  const inputRef = React.useRef<HTMLInputElement>(null)
  const listId = React.useId()
  const [ownQuery, setOwnQuery] = React.useState("")
  const query = controlledQuery ?? ownQuery
  const setQuery = (next: string) => { setOwnQuery(next); onQueryChange?.(next) }
  const [open, setOpen] = React.useState(false)
  const [active, setActive] = React.useState(0)
  const options = suggestions ? filterSuggestions(suggestions, query, value, maxSuggestions) : []
  const full = maxTags !== undefined && value.length >= maxTags
  const showList = open && options.length > 0 && !full
  const showEmpty = open && !!suggestions && !!emptyMessage && !!query.trim() && options.length === 0 && !full

  const commit = (raws: string[]) => {
    if (onSelect) {
      // Same normalisation and catalogue rules as tags, one value at a time.
      for (const picked of addTags([], raws, { suggestions, allowCreate })) onSelect(picked)
    } else {
      const next = addTags(value, raws, { suggestions, allowCreate, maxTags })
      if (next !== value) onValueChange?.(next)
    }
    setQuery("")
    setActive(0)
  }
  const onChange = (text: string) => {
    // Typed or pasted commas split entries; the text after the last comma stays in the field.
    const parts = text.split(",")
    if (parts.length > 1) commit(parts.slice(0, -1))
    setQuery(parts[parts.length - 1])
    setOpen(true)
    setActive(0)
  }
  const onKeyDown = (event: React.KeyboardEvent<HTMLInputElement>) => {
    if (event.key === "Enter") {
      event.preventDefault()
      if (showList && (query.trim() || !allowCreate)) commit([options[active]])
      else if (query.trim()) commit([query])
    } else if (event.key === "Backspace" && !query && value.length) {
      onValueChange?.(value.slice(0, -1))
    } else if (event.key === "ArrowDown" && options.length) {
      event.preventDefault()
      setOpen(true)
      setActive((i) => Math.min(i + 1, options.length - 1))
    } else if (event.key === "ArrowUp" && options.length) {
      event.preventDefault()
      setActive((i) => Math.max(i - 1, 0))
    } else if (event.key === "Escape") {
      setOpen(false)
    }
  }

  return (
    <div data-slot="tag-input" className={cn("relative", className)}>
      <div
        className="flex min-h-9 w-full flex-wrap items-center gap-1 rounded-md border border-input bg-card px-2 py-1 text-sm shadow-xs transition-[color,box-shadow] focus-within:border-ring focus-within:ring-[3px] focus-within:ring-ring/50 dark:bg-input/30"
        onClick={() => inputRef.current?.focus()}
      >
        {value.map((tag) => (
          <Badge key={tag} variant="secondary" className="gap-1 pr-1">
            {tag}
            <button type="button" aria-label={`${removeLabel} ${tag}`} disabled={disabled}
              className="rounded-sm opacity-70 outline-none hover:opacity-100 focus-visible:ring-2 focus-visible:ring-ring"
              onClick={() => onValueChange?.(value.filter((t) => t !== tag))}>
              <XIcon className="size-3" />
            </button>
          </Badge>
        ))}
        <input
          ref={inputRef}
          id={id}
          role="combobox"
          aria-label={ariaLabel}
          aria-expanded={showList}
          aria-controls={listId}
          aria-autocomplete="list"
          aria-activedescendant={showList ? `${listId}-${active}` : undefined}
          value={query}
          disabled={disabled || full}
          placeholder={value.length ? undefined : placeholder}
          className="min-w-24 flex-1 bg-transparent py-0.5 outline-none placeholder:text-muted-foreground disabled:cursor-not-allowed"
          onChange={(event) => onChange(event.target.value)}
          onKeyDown={onKeyDown}
          onFocus={() => setOpen(true)}
          onBlur={() => { setOpen(false); if (query.trim() && allowCreate && !onSelect) commit([query]) }}
        />
      </div>
      {showList && (
        <ul id={listId} role="listbox" className="absolute z-50 mt-1 max-h-60 w-full overflow-auto rounded-md border bg-popover p-1 text-popover-foreground shadow-md">
          {options.map((option, i) => (
            <li key={option} id={`${listId}-${i}`} role="option" aria-selected={i === active}
              className={cn("cursor-pointer rounded-sm px-2 py-1.5 text-sm", i === active && "bg-accent text-accent-foreground")}
              onMouseDown={(event) => { event.preventDefault(); commit([option]) }}
              onMouseEnter={() => setActive(i)}>
              {renderSuggestion ? renderSuggestion(option) : option}
            </li>
          ))}
        </ul>
      )}
      {showEmpty && (
        <div role="status" className="absolute z-50 mt-1 w-full rounded-md border bg-popover px-3 py-2 text-sm text-muted-foreground shadow-md">
          {emptyMessage}
        </div>
      )}
    </div>
  )
}

export { TagInput }
