// registry/react/ui/badge.tsx
import * as React from "react"
import { cva, type VariantProps } from "class-variance-authority"
import { cn } from "cn"
import { XIcon } from "lucide-react"
import { Slot } from "radix-ui"

const badgeVariants = cva(
  "inline-flex w-fit shrink-0 items-center justify-center gap-1 overflow-hidden rounded-full border border-transparent px-2 py-0.5 text-xs font-medium whitespace-nowrap transition-[color,box-shadow] focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 aria-invalid:border-destructive aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 [&>svg]:pointer-events-none [&>svg]:size-3",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground [a&]:hover:bg-primary/90",
        secondary:
          "bg-secondary text-secondary-foreground [a&]:hover:bg-secondary/90",
        destructive:
          "bg-destructive text-white focus-visible:ring-destructive/20 dark:bg-destructive/60 dark:focus-visible:ring-destructive/40 [a&]:hover:bg-destructive/90",
        outline:
          "border-border text-foreground [a&]:hover:bg-accent [a&]:hover:text-accent-foreground",
        ghost: "[a&]:hover:bg-accent [a&]:hover:text-accent-foreground",
        link: "text-primary underline-offset-4 [a&]:hover:underline",
        success: "border-transparent bg-success text-success-foreground [a&]:hover:bg-success/90",
        warning: "border-transparent bg-warning text-warning-foreground [a&]:hover:bg-warning/90",
        info: "border-transparent bg-info text-info-foreground [a&]:hover:bg-info/90",
        identity: "border-transparent bg-identity text-identity-foreground [a&]:hover:bg-identity/90",
      },
    },
    defaultVariants: {
      variant: "default",
    },
  }
)

// Saqara: `onRemove` adds a close button (removable chip) without making the badge taller.
function Badge({
  className,
  variant = "default",
  asChild = false,
  onRemove,
  removeLabel = "Retirer",
  children,
  ...props
}: React.ComponentProps<"span"> &
  VariantProps<typeof badgeVariants> & { asChild?: boolean; onRemove?: () => void; removeLabel?: string }) {
  const Comp = asChild ? Slot.Root : "span"

  return (
    <Comp
      data-slot="badge"
      data-variant={variant}
      className={cn(badgeVariants({ variant }), className)}
      {...props}
    >
      {children}
      {onRemove && !asChild && (
        <button type="button" aria-label={removeLabel} onClick={onRemove}
          className="-mr-0.5 inline-grid size-3.5 place-items-center rounded-full opacity-70 outline-none hover:opacity-100 focus-visible:opacity-100 focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-inset">
          <XIcon aria-hidden="true" className="size-3" />
        </button>
      )}
    </Comp>
  )
}

export { Badge, badgeVariants }

// registry/vue/ui/badge/Badge.vue
<script setup lang="ts">
import type { PrimitiveProps } from "reka-ui"
import type { HTMLAttributes } from "vue"
import type { BadgeVariants } from "."
import { reactiveOmit } from "@vueuse/core"
import { XIcon } from "@lucide/vue"
import { Primitive } from "reka-ui"
import { cn } from "@/lib/utils"
import { badgeVariants } from "."

// Saqara: `onRemove` (@remove) adds a close button (removable chip) without making the badge taller.
const props = withDefaults(defineProps<PrimitiveProps & {
  variant?: BadgeVariants["variant"]
  class?: HTMLAttributes["class"]
  onRemove?: () => void
  removeLabel?: string
}>(), { removeLabel: "Retirer" })

const delegatedProps = reactiveOmit(props, "class", "onRemove", "removeLabel")
</script>

<template>
  <Primitive
    data-slot="badge"
    :class="cn(badgeVariants({ variant }), props.class)"
    v-bind="delegatedProps"
  >
    <slot />
    <button v-if="onRemove && !asChild" type="button" :aria-label="removeLabel"
      class="-mr-0.5 inline-grid size-3.5 place-items-center rounded-full opacity-70 outline-none hover:opacity-100 focus-visible:opacity-100 focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-inset" @click="onRemove()">
      <XIcon aria-hidden="true" class="size-3" />
    </button>
  </Primitive>
</template>
